import React, { createContext, useCallback, useContext, useEffect, useRef, useState } from 'react';
import { supabase } from '../lib/supabase';
import { useAuth } from './AuthContext';
import { BOOKING_FEE_RATE } from '../constants/booking';

/**
 * ActiveBookingContext — one source of truth for the user's current parking
 * session, whether it's a real Supabase reservation or a "demo" booking
 * generated by reserving a placeholder spot (BERGEN_SPOTS, IDs like "p01").
 *
 * Why a context: HjemScreen wants to override the home view when a booking is
 * active; AktivParkeringScreen wants to show the live session; ProfileScreen
 * wants to list it. They all need the same data and to react to the same
 * changes (extend, end early, expire). A context unifies that.
 */

const ActiveBookingContext = createContext({
  booking: null,
  isDemo:  false,
  setDemoBooking: () => {},
  refresh: async () => {},
  extend:  async () => ({ ok: false }),
  endNow:  async () => ({ ok: false }),
});

export function ActiveBookingProvider({ children }) {
  const { user } = useAuth();
  const [booking, setBooking] = useState(null);
  const [isDemo, setIsDemo]   = useState(false);

  // We need a ref to the latest booking inside the supabase load callback so
  // it doesn't capture a stale closure when the channel fires repeatedly.
  const bookingRef = useRef(booking);
  useEffect(() => { bookingRef.current = booking; }, [booking]);

  // ── Real bookings: query + realtime ─────────────────────────────────
  const refresh = useCallback(async () => {
    if (!user) { return; }
    const now  = new Date().toISOString();
    const soon = new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString();
    const { data } = await supabase
      .from('reservations')
      .select('id, starts_at, ends_at, total, price_subtotal, status, spots(id, address, price_per_hour, amenities)')
      .eq('renter_id', user.id)
      .in('status', ['confirmed', 'pending'])
      .gte('ends_at', now)
      .lte('starts_at', soon)
      .order('starts_at', { ascending: true })
      .limit(1)
      .maybeSingle();

    if (data) {
      // A real booking takes precedence over any lingering demo state.
      setBooking(data);
      setIsDemo(false);
    } else if (!bookingRef.current || !bookingRef.current.id?.toString().startsWith('demo-')) {
      // Only clear if there isn't a demo booking we should keep.
      setBooking(null);
    }
  }, [user]);

  useEffect(() => {
    if (!user) { setBooking(null); setIsDemo(false); return; }
    refresh();
    const channel = supabase
      .channel(`active-booking-ctx-${user.id}-${Date.now()}`)
      .on('postgres_changes',
        { event: '*', schema: 'public', table: 'reservations', filter: `renter_id=eq.${user.id}` },
        refresh,
      )
      .subscribe();
    return () => { supabase.removeChannel(channel); };
  }, [user, refresh]);

  // Auto-expire bookings whose ends_at is in the past. Cheap minute-tick.
  useEffect(() => {
    const t = setInterval(() => {
      if (bookingRef.current && new Date(bookingRef.current.ends_at).getTime() < Date.now()) {
        setBooking(null);
        setIsDemo(false);
      }
    }, 30_000);
    return () => clearInterval(t);
  }, []);

  // ── Demo bookings: callers write directly ───────────────────────────
  const setDemoBooking = useCallback((b) => {
    setBooking(b);
    setIsDemo(true);
  }, []);

  // ── Mutations ───────────────────────────────────────────────────────
  const extend = useCallback(async (extraMins) => {
    if (!booking) return { ok: false, error: 'no_booking' };
    const price = booking.spots?.price_per_hour ?? 0;
    const newEnd = new Date(new Date(booking.ends_at).getTime() + extraMins * 60_000);
    const extraCost = Math.round(price * (extraMins / 60) * (1 + BOOKING_FEE_RATE));

    if (isDemo) {
      setBooking(b => b && ({ ...b, ends_at: newEnd.toISOString(), total: (b.total ?? 0) + extraCost }));
      return { ok: true };
    }

    const { error } = await supabase
      .from('reservations')
      .update({ ends_at: newEnd.toISOString(), total: (booking.total ?? 0) + extraCost })
      .eq('id', booking.id);
    if (error) return { ok: false, error: error.message };
    setBooking(b => b && ({ ...b, ends_at: newEnd.toISOString(), total: (b.total ?? 0) + extraCost }));
    return { ok: true };
  }, [booking, isDemo]);

  const endNow = useCallback(async () => {
    if (!booking) return { ok: false, error: 'no_booking' };

    if (isDemo) {
      setBooking(null);
      setIsDemo(false);
      return { ok: true };
    }

    const { error } = await supabase
      .from('reservations')
      .update({ ends_at: new Date().toISOString(), status: 'completed' })
      .eq('id', booking.id);
    if (error) return { ok: false, error: error.message };
    setBooking(null);
    return { ok: true };
  }, [booking, isDemo]);

  return (
    <ActiveBookingContext.Provider value={{ booking, isDemo, setDemoBooking, refresh, extend, endNow }}>
      {children}
    </ActiveBookingContext.Provider>
  );
}

export const useActiveBooking = () => useContext(ActiveBookingContext);
